# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package -Drevision=$GITHUB_REF --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -Drevision=$GITHUB_REF --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSS_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSS_TOKEN }}

